default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: oversea
#   pool: 50
#   host: localhost
#   username: root
#   password: ""


development:
  adapter: sqlite3
  pool: 5
  database: db/development.sqlite3
  timeout: 5000